## SYSTEM PROPERTIES 
##================== 
# SystemProperties\Get-SystemModelStack.ps1
# SystemProperties\Get-PSVersionStack.ps1 
# SystemProperties\Get-PSVersionandHostName.ps1 
# SystemProperties\Get-OSStack.ps1
# SystemProperties\Get-hostOSList.ps1
# SystemProperties\Get-OSBootTimes.ps1
# Config\Get-LocalAdminAndComputerStack.ps1
# Config\Get-LocalAdminStack.ps1
process\Get-ProcImgPathStack.ps1 
Config\Get-ProductStack.ps1