## SYSTEM PROPERTIES 
##================== 
SystemProperties\Get-WMIComputerSystem.ps1
SystemProperties\Get-WMIOperatingSystem.ps1
SystemProperties\Get-WMIBiosInfo.ps1
SystemProperties\Get-WMITimeZone.ps1
SystemProperties\Get-SystemBootTime.ps1
Config\Get-LocalAdmins.ps1
Config\Get-PSDotNetVersion.ps1
Process\Get-ProcImgPath.ps1
Config\Get-Products.ps1