##  =======================================================================================================
##  ---------------------------------------- MITRE Priv Escalation ----------------------------------------   
##  =======================================================================================================

Process\Get-Tasklistv.ps1

##  VV || Attempts to find InjectedThreads on each host  
Process\Get-InjectedThreads.ps1

##	VV || DLL search order hijacking
Process\Get-ProcsNModules.ps1

##	## || 'tasklist /v' but more verbose 'wmic process list full' - MISSING KANSA/PS IMPLEMENTATION
##  VV || seems equivalent to tasklist /v but xml output
Process\Get-Prox.ps1

##	VV || Acquires various details about running processes, including commandline arguments, process start time, parent process id and md5 hash of the processes image as found on disk.
Process\Get-ProcsWMI.ps1

##  VV || Gets a list of startup items from each host 
ASEP\Get-StartupCommand.ps1 

##  VV || Get list of scheduled tasks 
ASEP\Get-SchedTasks.ps1

##  VV Kansa get local admins on host - 'net localgroup administrators' 
Config\Get-LocalAdmins.ps1
 
##  VV || Kansa 'get-autoruns' provides significantly more ASEP 
ASEP\Get-Autorunsc.ps1

##  ## || ASEP = Auto Start Entry Point
##  VV || Kansa 'gwmi win32_service' - 'sc.exe query state= all'
ASEP\Get-SvcAll.ps1 

##  VV || The below Svc and WMI are used for finding persistence mechanisms. 
ASEP\Get-SvcFail.ps1
ASEP\Get-SvcTrigs.ps1

Process\Get-Handle.ps1
Log\Get-SysmonProcess.ps1 10080