##  =======================================================================================================
##  ----------------------------------------------- SigCheck ----------------------------------------------   
##  =======================================================================================================
ASEP\Get-Sigcheck.ps1 C:\Windows\


