Browser\Get-ChromeExtensionListingStack.ps1
Browser\Get-EdgeExtensionListingStack.ps1
Browser\Get-FirefoxExtensionListingStack.ps1
Browser\Get-EdgeUnknownExtensions.ps1
Browser\Get-ChromeUnknownExtensions.ps1 