##===============
## Basic Analysis 
##===============
# Audit\Audit-ClearTextPasswordsText.ps1 C:\Users
#Audit\Audit-ClearTextPasswordsDocXls.ps1 C:\Users
#Audit\Audit-ClearTextPasswordsDocxXlsx.ps1 C:\Users
#Audit\Audit-ClearTextPasswordsPDF.ps1 C:\Users
