# /////////////////////////////////////||\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# ////////////////////////////// Sysmon Analysis  \\\\\\\\\\\\\\\\\\\\\\\\\\\\
# /////////////////////////////////////||\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
Log\Get-SysmonNetStack.ps1
Log\Get-SysmonNet_LOLbins.ps1
Log\Get-SysmonNet_ForeignIpProcess.ps1
Log\Get-SysmonNet_LocalIpProcess.ps1
Log\Get-SysmonProcStack.ps1
Log\Get-SysmonProcs_LOLbins.ps1
Log\Get-SysmonProcsChildlessProcs.ps1