##  =======================================================================================================
##  ------------------------------------------------ SYSMON -----------------------------------------------   
##  =======================================================================================================
Log\Get-SysmonNetwork.ps1 10080
Log\Get-SysmonProcess.ps1 10080