##  =======================================================================================================
##	------------------------------------------ Packet Capture ---------------------------------------------
##  =======================================================================================================  
Net\Get-NetTracePacketCapture_Persistent.ps1 512
