##===============
## Basic Analysis 
##===============
#Log\Get-BrowserHistoryIEEdge.ps1
#Log\Get-BrowserHistoryChrome.ps1
#Log\Get-BrowserHistoryFireFox.ps1
#Log\Get-BrowserHistoryTitleStack.ps1
#Log\Get-BrowserHistoryURLStack.ps1
#ASEP\Get-ASEPImagePathLaunchStringMD5UnsignedStack.ps1
#ASEP\Get-ASEPImagePathLaunchStringPublisherStack.ps1 
#ASEP\Get-AutorunscStack.ps1
Process\Get-TaskListStack.ps1
Config\Get-LocalAdminStack.ps1
# Config\Get-ProductStack.ps1
Net\Get-NetstatListenerStack.ps1
Net\Get-NetstatStack.ps1
Net\Get-NetstatForeignIpProcess.ps1
ASEP\Get-StartupCommandStack.ps1
ASEP\Get-ScheduledTaskStack.ps1
# Log\Get-LogUserAssistValueStack.ps1
# ASEP\Get-WMISystemDrivers.ps1
# Net\Get-DNSCacheStack.ps1
# Meta\Get-PSProfileNameStack.ps1
# ASEP\Get-PSProfileScriptStack.ps1 
# Net\Get-ARPStack.ps1
# ASEP\Get-SvcAllCSVStack.ps1
# ASEP\Get-SvcAllRunningCSVStack.ps1
# CSVOutput\Get-SvcFailAllStack.ps1
# Net\Get-DNSServerSearchOrderStack.ps1
# Config\Get-IISStack.ps1
# SystemProperties\Get-OSStack.ps1
Log\Get-SysmonNetStack.ps1
Log\Get-SysmonNet_LOLbins.ps1
Log\Get-SysmonNet_ForeignIpProcess.ps1
Log\Get-SysmonNet_LocalIpProcess.ps1
Log\Get-SysmonProcStack.ps1
Log\Get-SysmonProcs_LOLbins.ps1
Log\Get-SysmonProcsChildlessProcs.ps1
#Log\Get-CriticalEventsStack.ps1
process\Get-ProcImgPathStack.ps1 
process\Get-ProcsWMIStack.ps1 
ASEP\Get-SvcFailAllStack.ps1
ASEP\Get-SvcTrigStack.ps1
config\Get-SMBShareStack.ps1