##  =======================================================================================================
##  ----------------------------------- MITRE Collection & Exfiltration -----------------------------------   
##  =======================================================================================================
Disk\List-100LargestArchives.ps1
#Disk\List-100LargestFiles.ps1
#Log\Get-RdpConnectionLogs.ps1
#Config\Get-SmbShare.ps1
#Config\Get-SharePermissions.ps1
#Disk\Get-DiskUsage.ps1
#Disk\Get-WebrootListing.ps1
#Disk\Get-WMILogicalDisk.ps1
#Disk\Get-WMIPhysicalMedia.ps1