##===========================
## SANS Unusual Network Usage 
##===========================
log\Get-BrowserHistoryTitleStack.ps1
log\Get-BrowserHistoryURLStack.ps1
Log\Get-BrowserHistoryIEEdge.ps1
Log\Get-BrowserHistoryChrome.ps1
Log\Get-BrowserHistoryFireFox.ps1
Log\Get-SysmonNetStack.ps1
Log\Get-SysmonNet_LOLbins.ps1
Log\Get-SysmonNet_ForeignIpProcess.ps1
Log\Get-SysmonNet_LocalIpProcess.ps1
CSVOutput\Get-NetstatListenerStack.ps1
CSVOutput\Get-NetstatStack.ps1
CSVOutput\Get-ARPStack.ps1
CSVOutput\Get-DNSCacheStack.ps1
config\Get-SMBShareStack.ps1