##===========================
## SANS Unusual Network Usage 
##===========================

## NET 
##====  
Net\Get-Netstat.ps1
Net\Get-ArpEXE.ps1
Net\Get-DNSCache.ps1
Net\Get-SmbSession.ps1
Net\Get-NetworkAdapterConfig.ps1
# Net\Get-NetRoutes.ps1

## CONFIG
##=======
Config\Get-SmbShare.ps1
Config\Get-SharePermissions.ps1
Config\Get-IIS.ps1 

## LOG
##====
Log\Get-RdpConnectionLogs.ps1
Log\Get-SysmonNetwork.ps1 10080
Log\Get-BrowserHistoryView.ps1