##  =======================================================================================================
##  =======================================================================================================
##	/////////////////////////////////////////////  PII Hunter  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
##  =======================================================================================================
##  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  B.E.R.T. //////////////////////////////////////////////
##  =======================================================================================================
##  =======================================================================================================

## Credit Cards
##=============
## -- One script to check text files, word documents, excel documents, and pdf files. Best for local scans and smallgroup scans
#	Audit\Audit-CCNum.ps1 C:\
## -- Multiple scripts to speed up remote audits and increase reliability
# Audit\Audit-CCNumText.ps1 C:\
# Audit\Audit-CCNumDocXls.ps1 C:\
# Audit\Audit-CCNumPDF.ps1 C:\
# Audit\Audit-CCNumDocxXlsx.ps1 C:\
## -- Check for CC terms, such as Visa, Discover Card, Master Card, Cvv, etc. 
#	Audit\Audit-CCKeyTerms.ps1 C:\

## SSN 
##====
#	Audit\Audit-SSN.ps1 C:\Users

## Possible Clear Text Passwords 
##==============================
#	Audit\Audit-ClearTextPasswords.ps1 C:\Users
# Audit\Audit-ClearTextPasswordsText.ps1 C:\Users
# Audit\Audit-ClearTextPasswordsDocXls.ps1 C:\Users
Audit-ClearTextPasswordsScripts.ps1 C:\Users
#Audit\Audit-ClearTextPasswordsDocxXlsx.ps1 C:\Users
#Audit\Audit-ClearTextPasswordsPDF.ps1 C:\Users
