##  =======================================================================================================
##  --------------------------------------- MITRE Lateral Movement ----------------------------------------   
##  =======================================================================================================
Net\Get-Netstat.ps1
Net\Get-SmbSession.ps1
Config\Get-SmbShare.ps1
Config\Get-SharePermissions.ps1 
Net\Get-NetworkAdapterConfig.ps1
Log\Get-CriticalEvents.ps1 
Config\Get-LocalAdmins.ps1
Config\Get-IIS.ps1 
Config\Get-UserQuery.ps1 
Process\Get-Tasklistv.ps1
Process\Get-ProcsWMI.ps1
Process\Get-ProcsNModules.ps1
Log\Get-RdpConnectionLogs.ps1 
Log\Get-LogUserAssist.ps1
Log\Get-SysmonNetwork.ps1 10080
Log\Get-SysmonProcess.ps1 10080 
Log\Get-BrowserHistoryView.ps1
