##  =======================================================================================================
##	------------------------------------------ Memory Capture ---------------------------------------------
##  =======================================================================================================
##  VV || This module will install the WinPMem driver on remote systems, then run Rekall to collect the process listing from memory. 
##  VV || (Has unsatisfied BINDEPs) 
#	Process\Get-RekalPslist.ps1 

##  VV || Requires Memoryze.exe dependancy - Can use Redline or Volitility 
#Memory\Get-Memoryze.ps1 

##  VV || Requires WinPMem
Memory\Get-MemoryWinPmem.ps1