##  =======================================================================================================
##  ------------------------------------------- MITRE Execution -------------------------------------------   
##  =======================================================================================================
Process\Get-ProcParents.ps1
##  VV || uses 'netstat -naob' which is same as Kansa get-netstat.ps1
Net\Get-Netstat.ps1

##  VV || Kansa 'tasklist.exe /v /fo csv' which is equivalent to 'wmi process list brief | findstr /R .'
##  VV || Tasklist /v - outputs to CSV 
Process\Get-Tasklistv.ps1

##	VV || Acquires various details about running processes, including commandline arguments, process start time, parent process id and md5 hash of the processes image as found on disk.
Process\Get-ProcsWMI.ps1

##  VV || Attempts to find InjectedThreads on each host  
Process\Get-InjectedThreads.ps1

##	VV || DLL search order hijacking
Process\Get-ProcsNModules.ps1

##  VV || Kansa 'get-autoruns' provides significantly more ASEP 
ASEP\Get-Autorunsc.ps1

##	VV || PrefetchListing => Application run data - https://www.forensicmag.com/article/2010/12/decoding-prefetch-files-forensic-purposes-part-1
Process\Get-PrefetchListing.ps1 

##  VV || Get-LogUserAssist.ps1 retrieves UserAssist data from ntuser.dat hives
##  VV || Gets programs that were recently executed on a system - https://www.magnetforensics.com/artifact-profiles/artifact-profile-userassist/
Log\Get-LogUserAssist.ps1 

##  VV || Windows MRU info 
Log\Get-LogOpenSavePidlMRU.ps1
Log\Get-OfficeMRU.ps1

##  ## || ASEP = Auto Start Entry Point
##  VV || Kansa 'gwmi win32_service' - 'sc.exe query state= all'
ASEP\Get-SvcAll.ps1 

##  VV || The below Svc and WMI are used for finding persistence mechanisms. 
ASEP\Get-SvcFail.ps1
ASEP\Get-SvcTrigs.ps1

#	ASEP\Get-WMIEvtFilter.ps1 
#	ASEP\Get-WMIFltConBind.ps1 
#	ASEP\Get-WMIEvtConsumer.ps1 

##  VV || Gets Powershell Profile information on each host  
ASEP\Get-PSProfiles.ps1

##  VV || Gets a list of startup items from each host 
ASEP\Get-StartupCommand.ps1 

##  VV || Get list of scheduled tasks 
ASEP\Get-SchedTasks.ps1

##  VV || Get Anti-Malware status 
Config\Get-AMHealthStatus.ps1
Config\Get-AMInfectionStatus.ps1

##  VV || Get listing of installed Applications on a host 
Config\Get-Products.ps1
 
##  VV || Lists users and their last authentication date/time   
Config\Get-UserQuery.ps1 

##  VV || Gets the system's Driver information  
Process\Get-WMISystemDrivers.ps1

##	## || 'tasklist /v' but more verbose 'wmic process list full' - MISSING KANSA/PS IMPLEMENTATION
##  VV || seems equivalent to tasklist /v but xml output
Process\Get-Prox.ps1

##	VV || Windows Event Logs -- CAN TAKE AWHILE 
Log\Get-LogWinEvent.ps1 Microsoft-Windows-Shell-Core/Operational
Log\Get-LogWinEvent.ps1 Microsoft-Windows-TerminalServices-LocalSessionManager/Operational

## VV || Sysmon 
Log\Get-SysmonProcess.ps1 10080
