##==================
## SANS Unusual ASEP  
##==================

## PROCESS
##========
Process\Get-WMISystemDrivers.ps1

## AUTO START ENTRY POINTS
##========================
ASEP\Get-StartupCommand.ps1
ASEP\Get-SchedTasks.ps1
ASEP\Get-PSProfiles.ps1  
ASEP\Get-Autorunsc.ps1 
ASEP\Get-WMIEvtFilter.ps1 
ASEP\Get-WMIFltConBind.ps1 
ASEP\Get-WMIEvtConsumer.ps1 
ASEP\Get-SvcAll.ps1 
ASEP\Get-SvcFail.ps1
ASEP\Get-SvcTrigs.ps1
 