##=======================
## SANS Unusual Processes 
##=======================

## PROCESS
##========
Process\Get-Tasklistv.ps1
Process\Get-ProcsWMI.ps1
Process\Get-InjectedThreads.ps1
Process\Get-ProcInfo.ps1
Process\Get-ProcImgPath.ps1
Process\Get-PsList.ps1 
Process\Get-Handle.ps1
Process\Get-WMISystemDrivers.ps1
Process\Get-PrefetchListing.ps1
Process\Get-ProcsNModules.ps1
Process\Get-Prox.ps1
# Process\Get-WMIRecentApps.ps1


## LOG
##====
Log\Get-SysmonProcess.ps1 10080 

 